### ISSUE TITLE
Add Keyboard Shortcuts.

### ISSUE THREAD

**Issue by AmolKumarGupta** [AmolKumarGupta/givemecode#13]
Shortcut 
- [x] For scrolling up
- [ ] Copy cmd
- [x] For direct entering in another Folder

**Comment by SinaElahimanesh** [comment]
Hello, can you explain it more?
Do you mean for example by clicking 'W' on the keyboard, the page should be scrolled up? 
And what about the two other check boxes? what do you mean by 'Copy cmd'?

**Comment by AmolKumarGupta** [comment]
# 2.  Copy CMD
when i click  `c` then it should automatically copy the main code present on the webpage .
> You can skip this part because we dont even start the php folder.

# 3. Redirection shortcut 
When i click `a+p` on the keyboard .
then user should be redirected to page https://givemecode.pages.dev/php .

**Comment by SinaElahimanesh** [comment]
Thanks for your explanations.
I have added a commit to my last Pull Request to solve this issue too (#13).
I added some pieces of javascript code to the bottom of index.html file.
So, if you press "U" on the keyboard after a second, the page will smoothly go to the top.
and if you press "A" it will redirect the page to [https://givemecode.pages.dev/php](url).
There was no way to press two keys simultaneously and do some actions. 

Therefore, please accept this Pull Request.

Thanks,
Sina
