### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by AmolKumarGupta** [AmolKumarGupta/givemecode#2]
1. Make a logo svg or jpg 
2. Add the logo as favicon

**Comment by Kunalll1** [comment]
Hay @AmolKumarGupta I seen this project... can I join this project?

**Comment by AmolKumarGupta** [comment]
yeah ofcourse @Kunalll1 , fork this project bro.

**Comment by Kunalll1** [comment]
I have an idea....if you are free then can you get into the meet? There we shall discuss about this project
`https://meet.google.com/nhh-ejeu-nmn`

**Comment by npkeerthi** [comment]
> 1. Make a logo svg or jpg
> 2. Add the logo as favicon

Is this work completed or could you give me this to complete. I can get this done in 30 mins

**Comment by AmolKumarGupta** [comment]
thanks @npkeerthi for help.
