### ISSUE TITLE
Topic discussion 

### ISSUE THREAD

**Issue by AmolKumarGupta** [AmolKumarGupta/givemecode#5]
@npkeerthi and @kunalll1 ,the basic meta is done 
Now the frontpage is not done yet But I will try to do it asap.
After that , i will deploy the Website 
if you have any suggestions, this issue will always open. 😃

**Comment by Kunalll1** [comment]
There is lot to do on the homepage if we are making a portfolio website then we have to add multiple things like :- Hero, Sliding testimonials, Responsive Layout, Grid type photo's gallery, Our Project word in list form.... and much more... **and in my opinion we shall recreate Template from envato element**

**Comment by AmolKumarGupta** [comment]
@Kunalll1 what is **envato** element bro ??
